name: Docker

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      #options: --privileged

    steps:
      - run: whoami
      - run: df -h
      - run: mount
      - run: mount /dev/root /mnt
      - run: ls /mnt
